### ISSUE TITLE
Methods to Return Tx Hash 

### ISSUE THREAD

**Issue by kevincmach** [FerranMarin/axie-utils-lib#1]
Would it be possible to return the Tx Hashes from any interactions made with the Ronin Chain? Like Payments, Claiming SLP, Transfers, etc. This would just help with accounting and logging. Thanks! Appreciate all the work put into this util package.

**Comment by FerranMarin** [comment]
Added in V2.
https://github.com/FerranMarin/axie-utils-lib/pull/5
