### ISSUE TITLE
Scatter.execute_ron does not accept float RON amount

### ISSUE THREAD

**Issue by iqbalhusen** [FerranMarin/axie-utils-lib#6]
```
to_ronin_amount_dict = {'0x6cad0145.....': 0.0001}
```

1. In the above dictionary, should the address be a ChecksumAddress or the address must be prefixed by `ronin:`?
2. If I want to transfer RON, can't the amount be in fractional RON? If not, then how to transfer say 0.0001 RON?
3. Is `Scatter.execute_ron` really used for transferring RON from one wallet to another (or more than one recipients as defined in the dictionary)?

Sorry if I missed something in the documentation.

**Comment by FerranMarin** [comment]
1) Either is fine, it expects the ronin: but the other one wil work just fine
2) Why not? Where do you see any limits? Or problems with that?
3) Scatter is a contract on the ronin chain tho to send to multiple addresses, n = 1 is still "multiple" but it's a waste to use it this way.
